# Exclude spec files from some Rubocop metric
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
Metrics/LineLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'lemmibot.gemspec'
# Allow prefixing writer method names with set_
Style/AccessorMethodName:
  Enabled: false
# Allow silently suppressing exceptions
Lint/HandleExceptions:
  Enabled: false
